"""empty message

Revision ID: 43b15fa96054
Revises: a554817db034
Create Date: 2020-04-03 15:52:46.064891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b15fa96054'
down_revision = 'a554817db034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_expiration', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password_reset_token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_column('user', 'password_reset_token')
    op.drop_column('user', 'password_reset_expiration')
    # ### end Alembic commands ###
