"""Added last login and date registered to user table

Revision ID: 749bb4c79f6b
Revises: 43b15fa96054
Create Date: 2020-04-07 18:46:03.002322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749bb4c79f6b'
down_revision = '43b15fa96054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_registered', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_date_of_birth'), 'user', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_user_date_registered'), 'user', ['date_registered'], unique=False)
    op.create_index(op.f('ix_user_last_login'), 'user', ['last_login'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_last_login'), table_name='user')
    op.drop_index(op.f('ix_user_date_registered'), table_name='user')
    op.drop_index(op.f('ix_user_date_of_birth'), table_name='user')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'date_registered')
    # ### end Alembic commands ###
