"""Added last login to user table

Revision ID: 7d136dbcb476
Revises: ea3fb5c2a21f
Create Date: 2020-04-06 16:42:22.763521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d136dbcb476'
down_revision = 'ea3fb5c2a21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_last_login'), 'user', ['last_login'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_login'), table_name='user')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
