"""added date of birth to user table

Revision ID: a554817db034
Revises: c16c221c7197
Create Date: 2020-03-20 00:10:27.704816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a554817db034'
down_revision = 'c16c221c7197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
