"""Added date registered to user table

Revision ID: ea3fb5c2a21f
Revises: a554817db034
Create Date: 2020-04-06 16:31:03.671258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3fb5c2a21f'
down_revision = 'a554817db034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_registered', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_date_of_birth'), 'user', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_user_date_registered'), 'user', ['date_registered'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_date_registered'), table_name='user')
    op.drop_index(op.f('ix_user_date_of_birth'), table_name='user')
    op.drop_column('user', 'date_registered')
    # ### end Alembic commands ###
